theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/math-integral-box"  # Diffrax logo in top left
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # These additions are my own custom ones, having overridden a partial.
    twitter_name: "@PatrickKidger"
    twitter_url: "https://twitter.com/PatrickKidger"

site_name: Diffrax
site_description: The documentation for the Diffrax software library.
site_author: Patrick Kidger

repo_url: https://github.com/patrick-kidger/diffrax
repo_name: patrick-kidger/diffrax
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4  # Prevents h5, h6 (i.e. methods) from showing up in the TOC.

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
        exclude:
            - "_overrides"
            - "_static/README.md"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4  # Makes everything top-level be <h4>. Child entries will be <h5> etc., but because of toc_depth, above, (deliberately) won't appear in the TOC.

nav:
    - 'index.md'
    - 'citation.md'
    - Usage:
        - 'usage/getting-started.md'
        - 'usage/how-to-choose-a-solver.md'
        - 'usage/manual-stepping.md'
        - 'usage/extending.md'
    - Examples:
        - Basic ODE/SDE/CDE examples: 'other_examples/basic-examples.md'
        - Coupled ODEs: 'examples/coupled_odes.ipynb'
        - Stiff ODE: 'examples/stiff_ode.ipynb'
        - Forcing terms: 'examples/forcing.ipynb'
        - Neural differential equations:
            - Neural ODE: 'examples/neural_ode.ipynb'
            - Neural CDE: 'examples/neural_cde.ipynb'
            - Neural SDE: 'examples/neural_sde.ipynb'
            - Latent ODE: 'examples/latent_ode.ipynb'
            - Continuous normalising flow: 'examples/continuous_normalising_flow.ipynb'
        - Symbolic regression: 'examples/symbolic_regression.ipynb'
        - Steady state: 'examples/steady_state.ipynb'
        - Kalman filter: 'examples/kalman_filter.ipynb'
        - Second-order sensitivities: 'examples/hessian.ipynb'
        - Nonlinear heat PDE: 'examples/nonlinear_heat_pde.ipynb'
    - Basic API:
        - 'api/diffeqsolve.md'
        - Solvers:
          - 'api/solvers/ode_solvers.md'
          - 'api/solvers/sde_solvers.md'
          - 'api/solvers/abstract_solvers.md'
        - 'api/saveat.md'
        - 'api/stepsize_controller.md'
        - 'api/solution.md'
        - 'api/autocitation.md'
    - Advanced API:
        - 'api/adjoints.md'
        - 'api/events.md'
        - 'api/terms.md'
        - 'api/path.md'
        - 'api/interpolation.md'
        - 'api/brownian.md'
        - 'api/nonlinear_solver.md'
        - 'api/progress_meter.md'
    - Further details:
        - 'further_details/faq.md'
        - 'further_details/acknowledgements.md'
        - 'further_details/benchmarks.md'
        - Developer Documentation:
            - 'devdocs/predictor_dirk.md'
            - 'devdocs/adjoint_commutative_noise.md'
            - Stochastic Runge-Kutta methods: 'devdocs/srk_example.ipynb'
